# Generated by Django 5.1.4 on 2024-12-15 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.developer'),
        ),
    ]
